spring.application.name=realticker-backend
huggingface.api.token=

# Render production config
server.port=${PORT:8080}
logging.level.com.siva.realticker=DEBUG
logging.level.org.springframework.web=DEBUG
spring.mvc.servlet.path=/